### PR TITLE
Search filter

### PR DESCRIPTION
**Pull request by baileyspace**

### CODE REVIEW

**Comment by tarakieffer** [comment]
Entity/Tag search includes items that do not have a matching tag or entity.  

Example search: https://stage.popuparchive.com/search?query=entity:%22british%20poetry%22,tag:%22british%20poetry%22,filter:OR

In reviewing the first 10 results - these items were returned that do not have a tag or entity of "british poetry"
https://stage.popuparchive.com/collections/2448/items/21800
https://stage.popuparchive.com/collections/938/items/22357
https://stage.popuparchive.com/collections/938/items/22356
https://stage.popuparchive.com/collections/1656/items/8618
https://stage.popuparchive.com/collections/938/items/22355
https://stage.popuparchive.com/collections/1656/items/8617
https://stage.popuparchive.com/collections/2064/items/23361

an example that is not multiple words: https://stage.popuparchive.com/search?query=entity:%22kalw%22,tag:%22kalw%22,filter:OR

The first ten results do not have any tags or entities assigned.
screen shot 2015-01-12 at 8 45 53 am

**Comment by tarakieffer** [comment]
Also, when I click on a facet when viewing the search results, the number of results get larger rather than smaller.  I presume this is because of the 'OR' which then would make sense, but I wanted to point it out because an user may be expecting it to narrow the search results.

**Comment by annewootton** [comment]
@tarakieffer, just to clarify, do you mean when you click on a "tag" or "entity" facet, or do you mean when you click on any facet? 

Seems like it should only happen when you click on a "tag" or "entity" facet, since this PR wouldn't affect sorting for facets like interviewer — but not positive.

**Comment by tarakieffer** [comment]
@annewootton Any facet, but only after having clicked on a tag or entity.  

Example: https://stage.popuparchive.com/search?query=entity:%22OONA%22,tag:%22OONA%22,filter:OR

screen shot 2015-01-12 at 2 24 35 pm

Then I click on interviewer: Terkel, Studs.  Instead of getting 20, I get 582 search results. 

https://stage.popuparchive.com/search?query=entity:%22OONA%22,tag:%22OONA%22,filter:OR,interviewer:%22Terkel,%20Studs%22&page=1
screen shot 2015-01-12 at 2 24 43 pm

**Comment by annewootton** [comment]
Oh, I get it. That sucks. Gotcha.

**Pull request closed without merging**
