### PR TITLE
Prerender task (moved to backend)

### PR DESCRIPTION
**Pull request by shindostrz**
Addresses #905

### CODE REVIEW

**Comment by pkarman** [comment]
when attempting to deploy this, I get an error:
```
       You have added to the Gemfile:
       * httparty
       Bundler Output: You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       
       You have added to the Gemfile:
       * httparty
 !
 !     Failed to install gems via Bundler.
 !
```

I think httparty is already included as a dependency elsewhere in Gemfile.lock so you might not need to list it explicitly in Gemfile. Otherwise, please run 'bundle install' as indicated in the error message and commit the change to Gemfile.lock.

**Comment by shindostrz** [comment]
I just removed the gem.

**Comment by pkarman** [comment]
Can we make this an async worker process? Any non-2xx response to prerender.io will generate a user-visible server error since right now it is on any Item.update. It's fine to have the after_update hook. Just have it create PrerenderItemWorker instead and let that class do the post.

Also, I'd suggest using the Rails url helpers to generate the callback url. The fewer places we have to change hardcoded strings, the better.

**Comment by pkarman** [comment]
reimplemented as 0b1acc8755ba91c5a8b60c58498e61678928e10c

**Pull request closed without merging**
