### PR TITLE
disallow org members from exceeding monthly upload limits #933

### PR DESCRIPTION
**Pull request by pkarman**

### CODE REVIEW

**Comment by tarakieffer** [comment]
Tara Test Org is over the monthly limit of 10 hours. 
screen shot 2015-02-02 at 3 29 40 pm

I expected Fritz as a member to get a message indicating limit has been reached and not able to upload files.   Instead I am getting the upload form with warning of the $22 rate.  Followed by a 404 message after clicking Save.

screen shot 2015-02-02 at 3 34 08 pm

I was able to successfully upload as the Owner of the org - Gwen.  Presuming this is as expected.

I am not able to upload as Wynifred - the admin, but that is because she has no credit card on file (perhaps this is a different bug)

screen shot 2015-02-02 at 3 48 56 pm

**Comment by annewootton** [comment]
For what it's worth, I do think that the admin of an org without CC on file should be able to go over the monthly limit. The assumption there is that they were invoiced/paid separately for a special enterprise plan, and we can invoice them for overages at the end of the month.

**Comment by tarakieffer** [comment]
For my understanding, which role of the organization should have a credit card on file?  In this case, the owner has a credit card on file, but the admin does not.  Should it be the other way around?

**Comment by annewootton** [comment]
Nope, that's right. Owners exist for billing purposes, admins exist for
workflow purposes.
ᐧ

**Comment by pkarman** [comment]
Users in an Org should have their active_credit_card? flag delegate to the Org.owner. I have made that change. Will re-deploy to stage once #968 has passed.

**Comment by pkarman** [comment]
see #983 instead

**Pull request closed without merging**
