### PR TITLE
Org admin can delete

### PR DESCRIPTION
**Pull request by pkarman**
addresses issue #829 

if a user is in an organization, they must have 'admin' role or be the org owner in order to delete a collection or an item.

if a user is not in an organization, they should be able to delete only their own collections and items.

### CODE REVIEW

**Comment by pkarman** [comment]
This is partly set up on stage at the db level.

https://stage.popuparchive.com/superadmin/organizations/32

Gwen is Owner, Wynifred is an admin. Needs one more User account to test the full set of scenarios.

Note that the Subscription plan for this org is now Small Business because it inherits from the owner (Gwen).

**Comment by pkarman** [comment]
Fritz added to org.

**Comment by tarakieffer** [comment]
Testing for both collections and items, organization member is able to create but not delete.  Admin is able to create AND delete.

Owner is able to create but not delete - this may be related to #917.

Users not associated with organization are able to created AND delete.

**Comment by pkarman** [comment]
fixes in place. let me know when I can push to stage.

**Comment by tarakieffer** [comment]
Latest change seems to have resolved the issue.  Through testing this is the behavior I am seeing which I understand to be as expected.
-Admin and owner of an organization are able to delete collections and items.
-Member of organization not able to delete collection or items. (Delete button disabled)
-User not associated with organization is able to delete collection and items.

@annewootton Should a member of an organization not be able to delete an audio file when editing an item?  In this latest branch, the user is able to delete the audio from the item.   
screen shot 2015-01-13 at 3 57 16 pm

**Comment by tarakieffer** [comment]
Updated comment for additional detail regarding which items can be deleted.

**Comment by annewootton** [comment]
I'm okay with leaving the delete button enabled at the file level for now, and @baileyspace & @Saltzshaker seem to agree. We can add a ticket to General To Do if anyone else feels strongly about it.

**Pull request merged**
